#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local

/etc/init.d/LeoFS.10.72.7.12 stop
sleep 3
route add -net 192.168.0.0 netmask 255.255.0.0 gw 10.72.7.254
route add -net 10.4.0.0 netmask 255.255.0.0 gw 10.72.7.254
route add -net 10.70.0.0 netmask 255.255.0.0 gw 10.72.7.254
route add -net 10.64.0.0 netmask 255.255.0.0 gw 10.72.7.254
route add -net 10.65.0.0 netmask 255.255.0.0 gw 10.72.7.254
route add -net 10.7.0.0 netmask 255.255.0.0 gw 10.72.7.254
/etc/init.d/LeoFS.10.72.7.12 start
sleep 10

mount 192.168.151.201:/vol/webserver/nginx1.2.7_mp4_TV  /export/home0/webserver/nginx  
mount /weilaitv/ysten/ /export/home0/docs/flv/flash/icntv/data/ysten --bind
mount /weilaitv/tvsee /export/home0/docs/flv/flash/icntv/data1 --bind

sleep 3
ulimit -SHn 65535
ulimit -c unlimited
/export/home0/webserver/nginx/sbin/nginx



/bin/su - zabbix -c "/etc/init.d/zabbix_agentd_ctl start"
`which java` -jar /usr/local/logstash/
